persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# Importante: Escutar na porta 1883 e permitir todos (sem senha por enquanto)
listener 1883
allow_anonymous true
